#!/usr/bin/env bash
# Auto-generated by Build_TRExFitter_Inputs.py.
#
# Redraw every SR/LowMVA plot using the Run2+Run3 MULTIFIT
# result instead of the single-run fit. Run AFTER run_all.sh.
#
# The combination itself stays a MultiFit - run2 and run3 are at
# different energies (13 vs 13.6 TeV) and so different signal
# cross sections, and per the supervisor must not be merged into
# one hand-written likelihood. Nothing here refits anything: the
# mu, its uncertainty and the limit stay the MultiFit's, and only
# the region plots are redrawn with its parameter values.
#
# TRExFitter has no `mp` step: a MultiFit combines workspaces and
# builds no histograms, so it cannot draw a region plot. A normal
# job can - it owns the histograms - but has no option to read a
# fit result from another directory (`FitResultsFile` is MultiFit
# only). `Suffix` is the hinge: the `p` step reads
# <Job>/Fits/<Job><Suffix>.txt, so staging the MultiFit result
# under that name is what makes this work.
#
# 20 invocations = 10 combinations x the 2 regions each spans,
# which live in 2 different job directories.
#
# `h` re-reads the cached histograms, so no ntuples are touched and
# nothing is refitted. Output: Plots/<region>_postFit_combFit.*,
# alongside (not replacing) the single-run post-fit plots.
set -euo pipefail
ROOT="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/.." && pwd)"
cd "$ROOT"

stage() {  # <multifit job> <fit job>
  src="$1/Fits/$1.txt"
  dst="$2/Fits/$2_combFit.txt"
  if [ ! -s "$src" ]; then
    echo "ERROR: $src missing - run the MultiFit first." >&2
    exit 1
  fi
  cp "$src" "$dst"
  # the .txt is what FitResults::ReadFromTXT reads; copy the
  # RooFitResult too when it exists, so nothing downstream can
  # fall back to the single-run one under the suffixed name
  [ -s "$1/Fits/$1.root" ] && cp "$1/Fits/$1.root" "$2/Fits/$2_combFit.root"
}

stage combine_1l2tau_XGB hh1l2tau_run2_XGB
trex-fitter hp configs/1l2tau_postfit_run2_XGB_combFit.config

stage combine_1l2tau_XGB hh1l2tau_run3_XGB
trex-fitter hp configs/1l2tau_postfit_run3_XGB_combFit.config

stage combine_1l2tau_DNN hh1l2tau_run2_DNN
trex-fitter hp configs/1l2tau_postfit_run2_DNN_combFit.config

stage combine_1l2tau_DNN hh1l2tau_run3_DNN
trex-fitter hp configs/1l2tau_postfit_run3_DNN_combFit.config

stage combine_1l2tau_MLP hh1l2tau_run2_MLP
trex-fitter hp configs/1l2tau_postfit_run2_MLP_combFit.config

stage combine_1l2tau_MLP hh1l2tau_run3_MLP
trex-fitter hp configs/1l2tau_postfit_run3_MLP_combFit.config

stage combine_1l2tau_GNN hh1l2tau_run2_GNN
trex-fitter hp configs/1l2tau_postfit_run2_GNN_combFit.config

stage combine_1l2tau_GNN hh1l2tau_run3_GNN
trex-fitter hp configs/1l2tau_postfit_run3_GNN_combFit.config

stage combine_1l2tau_PNN hh1l2tau_run2_PNN
trex-fitter hp configs/1l2tau_postfit_run2_PNN_combFit.config

stage combine_1l2tau_PNN hh1l2tau_run3_PNN
trex-fitter hp configs/1l2tau_postfit_run3_PNN_combFit.config

stage combine_2l2tau_XGB hh2l2tau_run2_XGB
trex-fitter hp configs/2l2tau_postfit_run2_XGB_combFit.config

stage combine_2l2tau_XGB hh2l2tau_run3_XGB
trex-fitter hp configs/2l2tau_postfit_run3_XGB_combFit.config

stage combine_2l2tau_DNN hh2l2tau_run2_DNN
trex-fitter hp configs/2l2tau_postfit_run2_DNN_combFit.config

stage combine_2l2tau_DNN hh2l2tau_run3_DNN
trex-fitter hp configs/2l2tau_postfit_run3_DNN_combFit.config

stage combine_2l2tau_MLP hh2l2tau_run2_MLP
trex-fitter hp configs/2l2tau_postfit_run2_MLP_combFit.config

stage combine_2l2tau_MLP hh2l2tau_run3_MLP
trex-fitter hp configs/2l2tau_postfit_run3_MLP_combFit.config

stage combine_2l2tau_GNN hh2l2tau_run2_GNN
trex-fitter hp configs/2l2tau_postfit_run2_GNN_combFit.config

stage combine_2l2tau_GNN hh2l2tau_run3_GNN
trex-fitter hp configs/2l2tau_postfit_run3_GNN_combFit.config

stage combine_2l2tau_PNN hh2l2tau_run2_PNN
trex-fitter hp configs/2l2tau_postfit_run2_PNN_combFit.config

stage combine_2l2tau_PNN hh2l2tau_run3_PNN
trex-fitter hp configs/2l2tau_postfit_run3_PNN_combFit.config

echo "MultiFit region plots:"
ls hh*/Plots/*_postFit_combFit.png
