#!/usr/bin/env bash
# Auto-generated by Build_TRExFitter_Inputs.py.
# Launch from anywhere - it cd's to the package root itself:
#   bash configs/run_all.sh   |   cd configs && bash run_all.sh
# One job per (channel, run, model): each config holds a single
# model, so no Regions=/Suffix= CLI options are needed.
# Steps per job are the supervisor's (n w d f p l) in ONE
# invocation: run as separate processes the fit writes no
# Fits/*.txt, because only `n` builds the NTUP histograms.
set -euo pipefail

# every path below (and NtuplePath / the MultiFit ConfigFile
# references inside the configs) resolves against the CWD, which
# must be the package root - the dir holding ntuples/ and configs/
ROOT="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/.." && pwd)"
cd "$ROOT"

# ---- trex-fitter environment --------------------------------
# trex-fitter is NOT in PATH in a fresh shell. On lxplus it ships
# inside the StatAnalysis release; set that up here so the script
# works from a clean login. Pin a release with e.g.
#   STATANALYSIS=StatAnalysis,0.5.3 bash configs/run_all.sh
if ! command -v trex-fitter >/dev/null 2>&1; then
  ALRB=/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase
  if [ -e "$ALRB/user/atlasLocalSetup.sh" ]; then
    echo "note: trex-fitter not in PATH - running asetup ${STATANALYSIS:-StatAnalysis,0.6.3}"
    set +eu  # ALRB/asetup are not set -eu clean
    export ATLAS_LOCAL_ROOT_BASE="$ALRB"
    source "$ALRB/user/atlasLocalSetup.sh" --quiet
    asetup "${STATANALYSIS:-StatAnalysis,0.6.3}"
    set -eu
  fi
fi
if ! command -v trex-fitter >/dev/null 2>&1; then
  echo "ERROR: trex-fitter not found in PATH (and no cvmfs to set it up from)." >&2
  echo "  This script needs a machine with TRExFitter - i.e. lxplus, not a" >&2
  echo "  local box. There: setupATLAS && asetup StatAnalysis,0.6.3" >&2
  echo "  (or pin: STATANALYSIS=StatAnalysis,<version> bash configs/run_all.sh)" >&2
  exit 1
fi
echo "using trex-fitter: $(command -v trex-fitter)"

# ---- locate the ntuples -------------------------------------
# NTUPLE_PATH=/some/where/ntuples bash configs/run_all.sh
# overrides the search below.
NTUPLES="${NTUPLE_PATH:-}"
if [ -z "$NTUPLES" ]; then
  # single line on purpose: a backslash continuation here got corrupted
  # in a clipboard transfer once and broke the whole script
  for cand in "$ROOT/ntuples" "$ROOT/configs/ntuples" "$ROOT/../ntuples" "$ROOT/ntuples/ntuples"; do
    if [ -d "$cand" ]; then NTUPLES="$cand"; break; fi
  done
fi
NTUPLES="$(readlink -f "${NTUPLES:-/nonexistent}")"
if [ ! -d "$NTUPLES" ]; then
  echo "ERROR: no ntuples directory found." >&2
  echo "  searched: \$ROOT/ntuples, \$ROOT/configs/ntuples, \$ROOT/../ntuples" >&2
  echo "  ROOT=$ROOT" >&2
  echo "  Copy ntuples/ next to configs/ (702 MB, 44 .root files), or:" >&2
  echo "    NTUPLE_PATH=/path/to/ntuples bash configs/run_all.sh" >&2
  exit 1
fi

# the configs say 'NtuplePath: ./ntuples', i.e. relative to this
# CWD - link whatever we found into place so that resolves
if [ "$NTUPLES" != "$ROOT/ntuples" ]; then
  ln -sfn "$NTUPLES" "$ROOT/ntuples"
  echo "note: linked $ROOT/ntuples -> $NTUPLES"
fi

# ---- preflight ----------------------------------------------
# TRExFitter only WARNS on a missing input and then fits empty
# histograms (single-bin auto-binning, no Fits/*.txt), so check
# every file the configs will open BEFORE burning 40 jobs.
INPUTS=(
  "Data/data_1l2tau_run2.root"
  "1l2tau/run2/signal_ggF.root"
  "1l2tau/run2/signal_VBF.root"
  "1l2tau/run2/ttbar.root"
  "1l2tau/run2/tops.root"
  "1l2tau/run2/singleH.root"
  "1l2tau/run2/diboson.root"
  "1l2tau/run2/VVV.root"
  "1l2tau/run2/Vgamma.root"
  "1l2tau/run2/Wjets.root"
  "1l2tau/run2/Zjets.root"
  "Data/data_1l2tau_run3.root"
  "1l2tau/run3/signal_ggF.root"
  "1l2tau/run3/signal_VBF.root"
  "1l2tau/run3/ttbar.root"
  "1l2tau/run3/tops.root"
  "1l2tau/run3/singleH.root"
  "1l2tau/run3/diboson.root"
  "1l2tau/run3/VVV.root"
  "1l2tau/run3/Vgamma.root"
  "1l2tau/run3/Wjets.root"
  "1l2tau/run3/Zjets.root"
  "Data/data_2l2tau_run2.root"
  "2l2tau/run2/signal_ggF.root"
  "2l2tau/run2/signal_VBF.root"
  "2l2tau/run2/ttbar.root"
  "2l2tau/run2/tops.root"
  "2l2tau/run2/singleH.root"
  "2l2tau/run2/diboson.root"
  "2l2tau/run2/VVV.root"
  "2l2tau/run2/Vgamma.root"
  "2l2tau/run2/Wjets.root"
  "2l2tau/run2/Zjets.root"
  "Data/data_2l2tau_run3.root"
  "2l2tau/run3/signal_ggF.root"
  "2l2tau/run3/signal_VBF.root"
  "2l2tau/run3/ttbar.root"
  "2l2tau/run3/tops.root"
  "2l2tau/run3/singleH.root"
  "2l2tau/run3/diboson.root"
  "2l2tau/run3/VVV.root"
  "2l2tau/run3/Vgamma.root"
  "2l2tau/run3/Wjets.root"
  "2l2tau/run3/Zjets.root"
)
missing=0
for f in "${INPUTS[@]}"; do
  if [ ! -r "$ROOT/ntuples/$f" ]; then
    echo "MISSING: $ROOT/ntuples/$f" >&2
    missing=$((missing + 1))
  fi
done
if [ "$missing" -ne 0 ]; then
  echo "ERROR: $missing of ${#INPUTS[@]} inputs missing under $NTUPLES" >&2
  echo "  (expected layout: ntuples/{1l2tau,2l2tau}/{run2,run3}/*.root + ntuples/Data/*.root)" >&2
  exit 1
fi
echo "preflight OK: ${#INPUTS[@]} inputs readable under $NTUPLES"

# ---- run ----------------------------------------------------
# trex-fitter exits 0 even when a job produces nothing, so check
# the fit result exists before moving on.
run_job() {  # <config> <job dir>
  echo "=== $1"
  trex-fitter nwdfpl "$1"
  if [ ! -s "$2/Fits/$2.txt" ]; then
    echo "ERROR: $1 produced no $2/Fits/$2.txt - stopping." >&2
    exit 1
  fi
}

run_job configs/1l2tau_limit_run2_XGB.config hh1l2tau_run2_XGB
run_job configs/1l2tau_limit_run2_DNN.config hh1l2tau_run2_DNN
run_job configs/1l2tau_limit_run2_MLP.config hh1l2tau_run2_MLP
run_job configs/1l2tau_limit_run2_GNN.config hh1l2tau_run2_GNN
run_job configs/1l2tau_limit_run2_PNN.config hh1l2tau_run2_PNN
run_job configs/1l2tau_limit_run3_XGB.config hh1l2tau_run3_XGB
run_job configs/1l2tau_limit_run3_DNN.config hh1l2tau_run3_DNN
run_job configs/1l2tau_limit_run3_MLP.config hh1l2tau_run3_MLP
run_job configs/1l2tau_limit_run3_GNN.config hh1l2tau_run3_GNN
run_job configs/1l2tau_limit_run3_PNN.config hh1l2tau_run3_PNN
run_job configs/1l2tau_limit_combined_XGB.config hh1l2tau_combined_XGB
run_job configs/1l2tau_limit_combined_DNN.config hh1l2tau_combined_DNN
run_job configs/1l2tau_limit_combined_MLP.config hh1l2tau_combined_MLP
run_job configs/1l2tau_limit_combined_GNN.config hh1l2tau_combined_GNN
run_job configs/1l2tau_limit_combined_PNN.config hh1l2tau_combined_PNN
run_job configs/2l2tau_limit_run2_XGB.config hh2l2tau_run2_XGB
run_job configs/2l2tau_limit_run2_DNN.config hh2l2tau_run2_DNN
run_job configs/2l2tau_limit_run2_MLP.config hh2l2tau_run2_MLP
run_job configs/2l2tau_limit_run2_GNN.config hh2l2tau_run2_GNN
run_job configs/2l2tau_limit_run2_PNN.config hh2l2tau_run2_PNN
run_job configs/2l2tau_limit_run3_XGB.config hh2l2tau_run3_XGB
run_job configs/2l2tau_limit_run3_DNN.config hh2l2tau_run3_DNN
run_job configs/2l2tau_limit_run3_MLP.config hh2l2tau_run3_MLP
run_job configs/2l2tau_limit_run3_GNN.config hh2l2tau_run3_GNN
run_job configs/2l2tau_limit_run3_PNN.config hh2l2tau_run3_PNN
run_job configs/2l2tau_limit_combined_XGB.config hh2l2tau_combined_XGB
run_job configs/2l2tau_limit_combined_DNN.config hh2l2tau_combined_DNN
run_job configs/2l2tau_limit_combined_MLP.config hh2l2tau_combined_MLP
run_job configs/2l2tau_limit_combined_GNN.config hh2l2tau_combined_GNN
run_job configs/2l2tau_limit_combined_PNN.config hh2l2tau_combined_PNN
# run2+run3 statistical combinations (need the per-run workspaces above)
trex-fitter mnwdfpl configs/1l2tau_combine_XGB.config
trex-fitter mnwdfpl configs/1l2tau_combine_DNN.config
trex-fitter mnwdfpl configs/1l2tau_combine_MLP.config
trex-fitter mnwdfpl configs/1l2tau_combine_GNN.config
trex-fitter mnwdfpl configs/1l2tau_combine_PNN.config
trex-fitter mnwdfpl configs/2l2tau_combine_XGB.config
trex-fitter mnwdfpl configs/2l2tau_combine_DNN.config
trex-fitter mnwdfpl configs/2l2tau_combine_MLP.config
trex-fitter mnwdfpl configs/2l2tau_combine_GNN.config
trex-fitter mnwdfpl configs/2l2tau_combine_PNN.config
